### ISSUE TITLE
контроллер загрузки файлов изображений

### ISSUE THREAD

**Issue by sergey-oreshkin** [ioreshkin/myfit-files#3]
файл должен быть загружен в минио и ответом на загрузку ссылка на файл в минио

**Comment by PavelSharko** [comment]
создал контроллер, и  сервис под него, 
сорян логи пока только в консоль и через систем принт , (их потом сразу вместе с эксепшн хендлером добавлю)
темтировтаь работоспособность через постман например

POST http://127.0.0.1:8080/api/files/upload
body;  from data
Key: file
Тип: File

он отдаст ссылку
